import { CircleDollarSign, Clock3, Receipt, Wallet } from "lucide-react";
import { MetricCard } from "../../components/MetricCard";
import { useDemoStore } from "../../data/DemoStoreContext";
import { estimateIncome } from "../../domain/calculations";

export function TeamIncomePage() {
  const { state, currentTeam } = useDemoStore(); const members = state.users.filter((user)=>currentTeam?.memberIds.includes(user.id));
  return <div className="page-stack"><div className="page-heading"><div><p className="page-kicker">只读资金视图</p><h1>团队收入</h1><span>汇总成员预估与已结算收入，不计算团长佣金</span></div></div><div className="metric-grid"><MetricCard label="本月预估收入" value="¥18,642" detail="较上月 +15.8%" icon={CircleDollarSign} /><MetricCard label="待结算金额" value="¥3,286" detail="126 条数据" icon={Clock3} tone="amber" /><MetricCard label="已结算金额" value="¥15,356" detail="8 个结算批次" icon={Receipt} tone="green" /><MetricCard label="成员可用余额" value="¥8,920" detail="团队成员合计" icon={Wallet} tone="violet" /></div><section className="content-card table-card"><div className="card-heading"><div><h2>成员收入汇总</h2><p>当前团队成员的模拟资金统计</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>成员</th><th>有效视频</th><th>有效时长</th><th>待结算</th><th>本月已结算</th><th>通过率</th></tr></thead><tbody>{members.map((member,index)=>{ const own=state.submissions.filter((item)=>item.ownerId===member.id); const pending=own.filter((item)=>item.settlementStatus==="unsettled").reduce((sum,item)=>sum+estimateIncome(currentTeam?.unitPricePerMinute ?? 12,item.durationSeconds,item.invalidSeconds,item.finalScore,item.qualityResult?.settlementRatio),0); return <tr key={member.id}><td><div className="member-cell"><span>{member.avatar}</span><div><strong>{member.name}</strong><small>{member.account}</small></div></div></td><td>{own.length+26+index*8} 条</td><td>{[23.4,26.8,18.7,15.2][index]}h</td><td>¥{(pending+index*86).toFixed(2)}</td><td><strong>¥{[3480,4216,2980,2610][index]}</strong></td><td>{[92.6,94.2,89.6,87.4][index]}%</td></tr>})}</tbody></table></div></section></div>;
}
